eips_code/eip-3540.py
Create separate function is_eof() which determines if a code is EOF.
Also consider any code with missing or invalid MAGIC to be legacy code.
=> EOF: Separate "is EOF" from EOF validation, fix prefix check

eips_code/eip-3540.py
This actually simplifies the code.
If we want to be more generic we can use `len(MAGIC)` instead of hardcoding `2` in some places, but I left these for now.
=> EIP-3540: Merge FORMAT and MAGIC

eips_code/eip4750.py, eips_code/eip4750_test.py
Diff with EIP-4200
```diff
--- eip4200.py	2022-07-08 19:08:32.611931186 +0200
+++ eip4750.py	2022-07-08 19:42:07.180663288 +0200
@@ -1,72 +1,78 @@
valid_opcodes = [
*range(0x00, 0x0b + 1),
*range(0x10, 0x1d + 1),
0x20,
*range(0x30, 0x3f + 1),
*range(0x40, 0x48 + 1),
*range(0x50, 0x5d + 1),
*range(0x60, 0x6f + 1),
*range(0x70, 0x7f + 1),
*range(0x80, 0x8f + 1),
*range(0x90, 0x9f + 1),
*range(0xa0, 0xa4 + 1),
-    *range(0xf0, 0xf5 + 1), 0xfa, 0xfd, 0xfe, 0xff
+    *range(0xf0, 0xf5 + 1), *range(0xfa, 0xff + 1),
]
-# STOP, RETURN, REVERT, INVALID, SELFDESTRUCT
-terminating_opcodes = [ 0x00, 0xf3, 0xfd, 0xfe, 0xff ]
+# STOP, RETURN, RETF, REVERT, INVALID, SELFDESTRUCT
+terminating_opcodes = [ 0x00, 0xf3, 0xfc, 0xfd, 0xfe, 0xff ]
immediate_sizes = 256 * [0]
immediate_sizes[0x5c] = 2  # RJUMP …
```
=> Add python code for EIP-4750

spec/eof.md
`code_section_index` => `taget_section_index`
=> Clarifying renaming in CALLF and JUMPF spec

spec/eof.md
At the risk of stating the obvious, here is one detail that was missing. The least obvious part is making explicit that we're not at this point planning any special hashing scheme for `InitcodeTransaction`
=> Backfill RLP and signature details for `InitcodeTransaction`

spec/eof.md
This is my clumsy take on explaining what happens with the data section. It turned out to be surprisingly hard to lay out.
=> Spec out and explain the rewriting of the data section

spec/eof.md
One of last pending discussion items. The changes are ported directly from https://github.com/ethereum/EIPs/pull/7820/files, only with an update to the language to match the mega spec.
As I understand, this proposition should accompany the revamping of `*CALL` instructions, otherwise there might be code regressions (from Vyper team).
There has been discussion on changing the RETURNDATA* semantics to pad with zero instead of halting on OOB, but this PR follows the EIP PR in keeping the (halt exceptionally) behavior. Unless there is a compelling reason to change to zero pad, I would keep it like that to not bloat the EOF change.
=> Port RETURNDATALOAD from EIP-7069 PR

spec/eof.md
We recently mentioned the need to liberate EOF (general) from format restrictions requiring a specific layout of header and body bytes (mainly to not obstruct Verkle-related optimizations in the future revisions of the EOF).
Most changes will need to be done in EIP-3540 wording, but this little change in the megaspec should also make it more clear it describes v1.
=> Clarify that EOF megaspec is EOFv1

spec/eof.md
This was updated in the EIP-7480 a while ago, but was overlooked in mega-spec https://github.com/ethereum/EIPs/pull/7803
=> Fix DATALOAD/DATALOADN prices

spec/eof.md
Otherwise, when CALLF is made and then JUMPF into a returning function, the expectation that CALLF results in a stack change of `outputs - inputs` is incorrect.
=> Fix error introduced when merging relaxed stack valid. into megaspec

spec/eof.md
Closes #43 
There is a [conflict of EXCHANGE and DATALOAD](https://github.com/ethereum/EIPs/pull/7819#discussion_r1446254404) and the E section is full.
It has been noted the E section could be for Emmediates, but we'd need to separate a bunch of opcodes otherwise related, and would likely run out of opcode slots in E section anyway quite soon.
My quick pitch for the move to D is to instead leave opcodes logically bound to EOF in `E` leaving plenty of space there for the future. As such, `D`ata ~and stack~ lands in D.
Let's quickly gather feedback on this. If there's objections, I'll do an alternative PR to do the Emmediates change and we go with that instead.
=> Move DATA* opcodes to the D section

spec/eof.md
This works more of a stop-gap solution to specify what the CALL2* replacement would look like, before we include the contents of EIP-7069 verbatim.
Important note: we had a discussion whether or not to allow the CALL2* in legacy. We didn't reach final consensus so let's use this PR to do so. My take on this continues to be to block CALL2* in legacy, to not inflate legacy. In case EOF does not make it or is delayed, EIP-7069 can be treated separately/ If EOF does make it, legacy should be as minimally impacted as possible.
=> Add a reference to EIP-7069

spec/eof.md
Looks like a trivial omission or is there any reasoning behind it not being on the list? We are currently requiring the replacement "*CALL2" opcodes
=> Put `STATICCALL` on the undefined opcode list

spec/eof.md
the end game should be:
1. Initcode beginning with `0xEF00` in legacy creation tx (in `data`) - invalid tx
2. Code beginning with `0xEF` deploy from legacy creation tx - abort (eip-3541)
3. Initcode beginning with `0xEF00` sent to CREATE / CREATE2 - soft fail
4. Code beginning with `0xEF` returned from CREATE / CREATE2 - abort (eip-3541)
I think now the megaspec covers all these cases
=> Spec out behavior of legacy CREATE/CREATE2 w/ eof initcode

spec/eof.md
Looks like some stale piece remained in the Megaspec. For consistency with `EXTCODEHASH/SIZE` behavior, `EXTCODECOPY` should also pretend the EOF code is `EF00`
=> Update EXTCODECOPY to EOF contract to copy `EF00`

spec/eof.md
Reasons to rename:
- current names were temporary names which lasted a bit too long
- avoid the sequel-based naming in instruction's mnemonics, conflicting with the `PUSH1, 2, 3...` convention
- avoid conflict with previous meaning of CREATE3 used in some contexts
EOFCREATE creating from within an EOF container
TXCREATE creating from a transaction
EXT* is for consistency with legacy `EXTCODEHASH` and the like
Lastly, abbreviated versions were slightly preferred (i.e. no `EXTDELEGATECALL`)
=> Rename CREATE3/4, *CALL2 instructions

spec/eof.md
Decided on the EOF implementers call after some time spent looking at the shorter versions.
=> Rename EXTS/DCALLs to longer versions

spec/eof.md
The description of EOF->legacy delegate-calling missed the fact that EXT*CALL status codes returned have changed. This fixed that
=> Fix specs on EXTDELEGATECALL->legacy

spec/eof.md
To align with EIP-4750 and implementations
=> Reduce RETF to 3 gas (VERY_LOW_TIER)

spec/eof.md
This addresses some feedback recently received - lack of examples.
To have CI validating the correctness of examples with least hassle, the examples sit in the `evmone` repo, as linked in here.
=> Add a link to examples

spec/eof.md
=> Restrict InitcodeTransaction's requirements on the `initcodes`

spec/eof.md
This doesn't need to be validation, since immediate of RJUMPV is `max_index` is uint8 and `count = max_index + 1`.
=> Remove deprecated RJUMPV count validation rule

spec/eof.md
initcode-mode works different from staticcall-mode, so requires an explicit clarification
=> Make explicit that initcode-mode is not transitive

spec/eof.md
Credit to @shemnon for pointing out that this was confusingly under-specified. Same fix will go into https://github.com/ethereum/EIPs/pull/8358 to update EIP-7620
=> Clarify how EOFCREATE/TXCREATE calldata works

spec/eof.md
Addressing some feedback for similar spec in https://github.com/ethereum/EIPs/pull/8498
=> Minor wording fixes in EOFCREATE spec

spec/eofv0_verkle.md
The design draft that proposes the use of EOF for storing code in Verkle Trees.
An alternative to the existing method of executing 31-byte code chunks accompanied by 1 byte of metadata.
=> EOFv0 for packaging legacy code in Verkle Trees

spec/eof.md
A limited #76, where we keep the TXCREATE, but discuss the necessity of having the Createor Contract introduced via an irregular state change.
Instead of the "ISC", we keep the possibility of "legacy-like" creation transaction, where the entire calldata is treated as an initcontainer (and wiped, so that it behaves as empty calldata within the execution frame of the initcontainer).
Can be informally thought of how sending EOF to an "empty address" would have the same effect as an "implicit `txcreate`" operating on the calldata.
~The lack of ability to put data in the calldata in this first iteration is substituted by putting the data into the `data_section` of the initcontainer.~ There are alternative ideas to this where "stray data" beyond the end of the declared `data_section` becomes …
=> Creation transaction instead of the irregular state change

spec/eof.md
The EIPs are for most part up-to-date (or updated almost in parallel to the mega spec), so I think it warrants removing the disclaimers from the text.
Also removing some possibly confusing (at this point) narrative on versions.
=> Update narrative on EIPs up-to-dateness and relevance

spec/eof.md
Add the one essential ASE carve out -
EXT*CALL should halt when hugh bytes are set.
=> Add ASE carve out

spec/eof.md, spec/eof_future_upgrades.md
require EOFCREATE to point to initcode, and RETURNCONTRACT to point to runtime code.
=> feat: define initcode mode and require validation of RETURNCONTRACT

spec/eof.md
Fix potential typos in eof.md:
- Typo in 2.3 of Stack validation
- Potentially incorrect formula in 4.2.2
=> Typos in eof.md

spec/eof.md
use zero-padding instead of exceptional halt
=> feat: change oob behavior of RETURNDATALOAD and RETURNDATACOPY

spec/eof.md
Aligns with https://github.com/ethereum/EIPs/pull/8621/files
=> Clarify that EXTDELEGATECALL fails EOF->EOA/empty too

spec/eof.md
not sure about the wording for the mid-creation stuff. Don't want to over-formalize it, as it is a clarification, not spec.
=> Clarify RJUMP successors and EXTCODE* for mid-creation targets

spec/eof.md
Pushing in form of a PR after discussion during [EOF implementers call 49](https://github.com/ethereum/pm/issues/1055).
To reiterate the reasoning behind:
- subcontainer have size limit of 64K implied by the header format
- but this doesn't apply to "top-level" containers!
- we have EIP-3860 MAX_INITCODE_SIZE of 48K - but not part of EOF validation!
- EVM implementations doing `validate_eof` and handling the containers/headers must make assumptions about the maximum size of the container to expect and handle
- is it MAX_INITCODE_SIZE?
- is it 64K, same as subcontainer?
- is it whatever can be maxed out with sections, i.e. max code sections, then max of max container sections and max data size?
- is it some yet other value?
- for example, evmone had a [subtle …
=> Require MAX_INITCODE_SIZE limit to be satisfied during validation

spec/eof.md
I noticed the note to the last addition wasn't making any significant point. Clarified here.
But actually, I'm considering removing it and keeping it simple. If anyone prefers to keep it, let me know
=> Remove the NOTE about MAX_INITCODE_SIZE checking

spec/eof.md
Extracted from #129, see discussion there. From description:
> adds a [rule proposed on the EOF impl call](https://github.com/ethereum/pm/issues/1055#issuecomment-2150340561) (option 2.) to disallow subcontainers referenced by both RETURNCONTRACT and EOFCREATE.
=> Disallow being referenced by both RETURNCONTRACT and EOFCREATE

spec/eof.md, spec/eof_future_upgrades.md
Extracted from #129 - just the editorial changes which remove definitions. The "breaking" change is now in #135.
CC @gumb0 @shemnon PTAL, you've reviewed the other PRs, still looks good like this?
=> Remove initcode/runtime definitions and simplify wording

spec/eof.md
Reflects that in order to encode 255 num container sections, one does not use 0x00FF, but 0x0100, due to the rule that the num container sections encoded should be at lest 0x0000, in order to avoid 0x030000
=> update num container sections

spec/eof.md
This is a follow up of #141 There were other entries off in this table. I also think we should not duplicate the ranges in the bullet points above, so I removed these and had the reader refer to the table.
WDYT?
=> Remove duplicate formulation of admissible header item entries

spec/implementation_matrix.md
Kind request to implementation owners to double-check if mentioned revisions of tests pass and provide input on completeness (apologies if my first take is off here, also I have no accurate knowledge on erigon/geth/nethermind/EELS).
Also, if any other client is exporting fixtures like `evmone`, feel free to let know and add to the table (this is to enable us to find issues earlier, meanwhile work on providing coverage with EEST is ongoing)
=> Add EOF testing completeness matrix

README.md
Found this small typo while reading the readme.
=> docs: add missing parenthesis to readme

spec/eof.md
This looks to be a typo that we forgot to fix. EIP doesn't have this problem, it only describes the check in words.
=> Fix stack validation check for backwards jumps

spec/implementation_matrix.md
Update tests.
Note evmone tests green check doesn't cover TXCREATE issues.
Signed-off-by: Danno Ferrin <danno@numisight.com>
=> Update Besu Matrix Values

spec/implementation_matrix.md
`EEST`, have run a slightly newer test suite from this PR: https://github.com/ethereum/execution-spec-tests/pull/768
`ethereum/tests` are run on every Revm PR:
statetests: https://github.com/bluealloy/revm/blob/89b65e1e4b5bbb2ddba4f414ca41ce3f8ad9758d/.github/workflows/ethereum-tests.yml#L51
EOF validation: https://github.com/bluealloy/revm/blob/89b65e1e4b5bbb2ddba4f414ca41ce3f8ad9758d/.github/workflows/ethereum-tests.yml#L58
=> chore: Update Revm testing matrix

spec/implementation_matrix.md
EELS has all the EIPS in the EOF implemented. The [PR](https://github.com/ethereum/execution-specs/pull/972) is currently under review. The EOF eips have been implemented on top of the Prague EIPs (2537, 2935, 6110, 7002, 7251, 7685)  that have already been implemented earlier. 
The implementation currently passes the following test suits
- EEST published fixtures v1.0.8 (EOF and State tests)
- ethereum/tests v14.1 (EOF and State tests)
- evmone published fixtures v0.12.0 (EOF and State tests)
=> eels eof implementation update 2

spec/implementation_matrix.md
Just some housekeeping.
The stEOF tests are [in the process of being migrated](https://github.com/ethereum/tests/pull/1410), but I think we can anticipate concluding that and remove links right away.
=> Update links to tests in implementation_matrix.md

spec/implementation_matrix.md
Updated and groomed the implementation_matrix.md to my best current knowledge.
=> EOF testing table and links

spec/implementation_matrix.md
Update the newest EELS PR that implements EOF on top of Prague. Also update the test status.
EELS passes all of the EEST 2.2.0 version of the tests.
=> update EELS eof status

spec/eof.md
It has been brought to attention in https://ethereum-magicians.org/t/eip-7620-eof-contract-creation-instructions/18625/4 that the stack args of EOFCREATE do not align with CREATE2. This is something good, since args of those opcodes have unintuitively distinct meaning - namely the input buffer.
However we seem to be missing out on an opportunity to align the EOFCREATE stack args with another closely related opcode: EXTCALL. They differ only by a single argument (`salt` vs `target_address`) per [EIP-7069](https://eips.ethereum.org/EIPS/eip-7069), so we could aim to make them aligned.
=> Align EOFCREATE stack args with EXTCALL

spec/eof.md
Aligns with https://github.com/ethereum/EIPs/pull/9600, planned for eof-devnet-1
=> Change to max_stack_increase

spec/eof.md
Align with https://github.com/ethereum/EIPs/pull/9581, for eof-devnet-1
=> Make container section size 4 bytes wide

spec/eof.md
See EIP update for justification https://github.com/ethereum/EIPs/pull/9656
=> Remove redundant stack overflow check

spec/eof.md
No mention of status codes is confusing.
=> Add status codes to EXT*CALL spec
